# Generated by Django 4.2.6 on 2023-10-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protraveller_app', '0002_article_profile_favorite_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
