# Generated by Django 4.0.6 on 2023-11-08 13:26

from django.db import migrations
from django.db import migrations
from protraveller_app.models import CustomUser
from django.contrib.auth.models import User

def transfer_user_data(apps, schema_editor):
    for user in User.objects.all():
        CustomUser.objects.create(
            id=user.id,
            username=user.username,
            email=user.email,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('protraveller_app', '0008_alter_article_author'),  # Replace this with your actual previous migration
    ]

    operations = [
        migrations.RunPython(transfer_user_data),
    ]
